### ISSUE TITLE
Cannot fins script for MainCam

### ISSUE THREAD

**Issue by jialuwang123321** [chstetco/virtualradar#3]
Dear Christian Schöffmann,

  Thank you so much for your fantastic simulator. May I consult you a question?

  I have opened a new project in Unity3d and loaded all from Github. However, **I found that the MainCam prefab doesn't have any script.** 
  May I know **which script should I attach to the MainCam** to finally get the output radio data?
  Thank you in advance!

Best
Jialu

**Comment by chstetco** [comment]
Hey Jialu,

Thank you very much for you interest in our framework and for this notice.
Indeed, the MainCam prefab was missing the script, we are very sorry for that! 

I pushed the changes of the prefab to the repo, now when you import the prefab to your project you should see that the MainCam has the 'ScreenSpaceRadarControlPlot' script attached to it which allows you to adjust the parameters of the sensor.

Best Regards,
Christian
